[project]
name = "procreate-rename"
version = "0.1.0"
description = "A script for renaming all procreate files in a directory based on their creation date"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
